/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blazartech.products.blazarsql.components.gui;

import com.blazartech.products.blazarsql.Constants;
import javax.swing.JPanel;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author AAR1069
 */
@Component
@Scope("prototype")
public class AboutPanel extends JPanel implements InitializingBean {

    /**
     * Creates new form AboutPanel
     * @throws java.lang.Exception
     */
    @Override
    public void afterPropertiesSet() throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText(aboutText);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private final String aboutText = "<html><center>" + Constants.PROGRAM_NAME + ", version " + Constants.PROGRAM_VERSION + "<br>by " + Constants.AUTHOR + "<br><i>copyright &copy; " + Constants.COPYRIGHT_RANGE + "</i></center>";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
