/*
 * DatabaseConnectionInfoPanel.java
 *
 * Created on April 12, 2004, 10:49 AM
 */

package com.blazartech.products.blazarsql.components.gui;

import com.blazartech.products.blazarsql.components.dataobjects.DBConnection;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 * Show information about a connection.
 * @author Dr. Scott E. Aaron
 * @version $Id: DatabaseConnectionInfoPanel.java 30 2015-04-23 19:52:54Z aar1069 $
 */

/* $Log: DatabaseConnectionInfoPanel.java,v $
/* Revision 1.5  2008/02/11 22:24:01  aar1069
/* use imports
/*
/* Revision 1.4  2006/10/05 18:10:27  aar1069
/* *** empty log message ***
/*
/* Revision 1.3  2006/09/20 18:43:34  aar1069
/* Fix the font on some labels.
/*
/* Revision 1.2  2006/09/19 17:54:51  aar1069
/* Add the connection URL to the display.
/*
 *******************************************************************************/

public class DatabaseConnectionInfoPanel extends JPanel {
    
    /**
     * Creates new form DatabaseConnectionInfoPanel
     * @param p The connection panel to which this panel is associated.
     * @throws java.sql.SQLException 
     */
    public DatabaseConnectionInfoPanel(DatabaseConnectionPanel p) throws SQLException {
        initComponents();
        
        // populate.
        DBConnection dbConn = p.getDatabaseConnection();
        Connection jdbcConn = dbConn.getJDBCConnection();
        userIdLabel.setText(dbConn.getUserID());
        serverNameLabel.setText(dbConn.getServerName());
        databaseNameLabel.setText(dbConn.getDatabaseName());
        databaseTypeNameLabel.setText(dbConn.getDatabaseTypeName() + " (" + jdbcConn.getMetaData().getDatabaseProductName() + " " + jdbcConn.getMetaData().getDatabaseProductVersion() + ")");
        jdbcDriverLabel.setText(jdbcConn.getMetaData().getDriverName() + " " + jdbcConn.getMetaData().getDriverVersion()); 
        jdbcUrlLabel.setText(dbConn.getConnectionURL());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        _userIdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        _serverPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        serverNameLabel = new javax.swing.JLabel();
        _databasePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        databaseNameLabel = new javax.swing.JLabel();
        _databaseTypePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        databaseTypeNameLabel = new javax.swing.JLabel();
        _jdbcDriverPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jdbcDriverLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jdbcUrlLabel = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        _userIdPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 7, 5));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("user");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 16));
        _userIdPanel.add(jLabel1);

        userIdLabel.setFont(new java.awt.Font("Arial", 0, 12));
        _userIdPanel.add(userIdLabel);

        add(_userIdPanel);

        _serverPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 7, 5));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("server");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 16));
        _serverPanel.add(jLabel3);

        serverNameLabel.setFont(new java.awt.Font("Arial", 0, 12));
        _serverPanel.add(serverNameLabel);

        add(_serverPanel);

        _databasePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 7, 5));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("database");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 16));
        _databasePanel.add(jLabel5);

        databaseNameLabel.setFont(new java.awt.Font("Arial", 0, 12));
        _databasePanel.add(databaseNameLabel);

        add(_databasePanel);

        _databaseTypePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 7, 5));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("database type");
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 16));
        _databaseTypePanel.add(jLabel7);

        databaseTypeNameLabel.setFont(new java.awt.Font("Arial", 0, 12));
        _databaseTypePanel.add(databaseTypeNameLabel);

        add(_databaseTypePanel);

        _jdbcDriverPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("JDBC Driver");
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 16));
        _jdbcDriverPanel.add(jLabel2);

        jdbcDriverLabel.setFont(new java.awt.Font("Arial", 0, 12));
        _jdbcDriverPanel.add(jdbcDriverLabel);

        add(_jdbcDriverPanel);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("JDBC URL");
        jLabel4.setMaximumSize(new java.awt.Dimension(80, 15));
        jLabel4.setMinimumSize(new java.awt.Dimension(80, 15));
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel1.add(jLabel4);

        jdbcUrlLabel.setFont(new java.awt.Font("Arial", 0, 12));
        jPanel1.add(jdbcUrlLabel);

        add(jPanel1);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _databasePanel;
    private javax.swing.JPanel _databaseTypePanel;
    private javax.swing.JPanel _jdbcDriverPanel;
    private javax.swing.JPanel _serverPanel;
    private javax.swing.JPanel _userIdPanel;
    private javax.swing.JLabel databaseNameLabel;
    private javax.swing.JLabel databaseTypeNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jdbcDriverLabel;
    private javax.swing.JLabel jdbcUrlLabel;
    private javax.swing.JLabel serverNameLabel;
    private javax.swing.JLabel userIdLabel;
    // End of variables declaration//GEN-END:variables
    
}
