/*
 * SliderPositionSelectionPanel.java
 *
 * Created on August 27, 2008, 12:24 PM
 */

package com.blazartech.products.blazarsql.components.gui;

import javax.swing.JPanel;

/**
 * Panel to select the default editor width.
 *
 * @author  Dr. Scott E. Aaron
 * @revision $Id: SliderPositionSelectionPanel.java 30 2015-04-23 19:52:54Z aar1069 $
 */

/* $Log: SliderPositionSelectionPanel.java,v $
/* Revision 1.2  2008/08/27 18:08:36  AAR1069
/* no message
/*
 *******************************************************************************/
public class SliderPositionSelectionPanel extends JPanel {
    
    /** Creates new form SliderPositionSelectionPanel */
    public SliderPositionSelectionPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        _slider = new javax.swing.JSlider();
        _positionLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        _slider.setMinorTickSpacing(10);
        _slider.setPaintTicks(true);
        _slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                _sliderStateChanged(evt);
            }
        });

        add(_slider, java.awt.BorderLayout.CENTER);

        _positionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _positionLabel.setText("jLabel1");
        add(_positionLabel, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents

    private void _sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event__sliderStateChanged
        // TODO add your handling code here:
        setOffset(((float) _slider.getValue()) / 100f);
        _positionLabel.setText(_slider.getValue() + "% of width");
    }//GEN-LAST:event__sliderStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _positionLabel;
    private javax.swing.JSlider _slider;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property offset.
     */
    private float offset;

    /**
     * Getter for property offset.
     * @return Value of property offset.
     */
    public float getOffset() {
        return this.offset;
    }

    /**
     * Setter for property offset.
     * @param offset New value of property offset.
     */
    public void setOffset(float offset) {
        this.offset = offset;
        _slider.setValue((int) (offset * 100f));
    }
    
}
